on:
    workflow_call:

jobs:
    build:
        name: Build and test Golang App
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
