name: Build

on:
    workflow_call:
        inputs:
            GO_VERSION:
                required: true
                type: string
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Go ${{ inputs.GO_VERSION }}
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ inputs.GO_VERSION }}

            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
