name: Deploy

on:
    workflow_call:
        inputs:
            DOCKER_COMPOSE_PATH:
                required: true
                type: string
        secrets:
            SSH_HOST:
                required: true
            SSH_USERNAME:
                required: true
            SSH_KEY:
                required: true
            SSH_PORT:
                required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Redeploy Docker
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ inputs.DOCKER_COMPOSE_PATH }}
                      docker compose pull && docker compose restart || exit 1
