on:
    push:
        branches: ['main']

jobs:
    build:
        uses: https://github.com/theadell/kickbot/.github/workflows/build.yml@v1
    release:
        uses: https://github.com/theadell/kickbot/.github/workflows/release.yml@v1
