on:
    push:
        branches: ['main']

jobs:
    build:
        uses: ./.github/workflows/build.yml
    release:
        needs: build
        uses: ./.github/workflows/release.yml
        secrets: inherit
    deploy:
        needs: release
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
