on:
    workflow_call:

jobs:
    release:
        name: Build and publish Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ${{ env.IMAGE_NAME }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  tags: ${{ steps.meta.outputs.tags }}
                  annotations: ${{ steps.meta.outputs.annotations }}
                  push: true
