name: Trigger PR (main)

on:
    pull_request:
        branches: ["main"]

jobs:
    build:
        uses: ./.github/workflows/job.build.yml
        with:
            GO_VERSION: ${{ vars.GO_VERSION }}
