name: Trigger Push (main)

on:
    push:
        branches: ["main"]

jobs:
    build:
        uses: ./.github/workflows/job.build.yml
        with:
            GO_VERSION: ${{ vars.GO_VERSION }}
    release:
        needs: build
        uses: ./.github/workflows/job.release.yml
        with:
            DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        secrets:
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    deploy:
        needs: release
        uses: ./.github/workflows/job.deploy.yml
        secrets:
            DOCKER_COMPOSE_PATH: ${{ secrets.DOCKER_COMPOSE_PATH }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
            SSH_PORT: ${{ secrets.SSH_PORT }}
